### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel

### ISSUE THREAD

**Issue by nuwak** [U-ways/kotlin-quarkus-realworld-example-app#13]
Please update your Kotlin version

https://youtrack.jetbrains.com/issue/KT-45566/JDK-16-e-javalangNoClassDefFoundError-Could-not-initialize-class-orgjetbrainskotlincomintellijpomjavaLanguageLevel#focus=Comments-27-4781545.0-0

I had the same error

**Comment by u-ways** [comment]
This project does not run on JDK 16 or Kt 1.5.0-M1. (as described in the issue you linked to)
Please run on JDK 11 & Kt 1.4.32 as I managed to run the project just fine in a clean environment with the excepted versions. 

Otherwise, if you're interested, please feel free to pick up this ticket: #2
