### ISSUE TITLE
Integrate with a Kotlin linter

### ISSUE THREAD

**Issue by u-ways** [u-ways/kotlin-quarkus-realworld-example-app#5]
It would be nice to have a linter to keep the project as consistent as possible. A widely popular Kotlin linter is [Pinterest's ktlint](https://github.com/pinterest/ktlint). It has a built-in rule sets, formatter tasks, reporters, and allows extension with custom rule sets and reporters.

#### Requirements
- Set CI to run the linter after tests has passed. (must be a Makefile recipe)
- Provide an `.editorconfig` to allow IDE users adhere to the standards for a smoother dev experience.

Please see [the user guide](https://pinterest.github.io/ktlint/) for further details.

**Comment by DeKaN** [comment]
Hi, can I take this issue?

**Comment by u-ways** [comment]
Hello @DeKaN , of course you can. This is now assigned to you.

**Comment by DeKaN** [comment]
@u-ways I want to provide Ktlint as Gradle plugin. What CI are you planing to use?

**Comment by u-ways** [comment]
> @u-ways I want to provide Ktlint as Gradle plugin. What CI are you planing to use?

@DeKaN Please use GitHub actions, it has not been setup as of yet in this project. 

Would you be interested in completing #1 first and then come back to this ticket? (I have added some guidelines to help with setting up GH actions and happy to help / answer any questions)

**Comment by DeKaN** [comment]
OK, I'll start with #1 :)  Should I fix ktlint issues in code in this issue?

**Comment by u-ways** [comment]
@DeKaN Awesome! As in fix the ktlint issues in #1? If so, no, please fix them in this issue (#5) to isolate the ktlint changes to this PR only. Otherwise, yes, please fix the ktlint issues here.

**Comment by u-ways** [comment]
> OK, I'll start with #1 :) Should I fix ktlint issues in code in this issue?

Don't forget to comment or link your PR branch to #1 so I can assign the issue to you. (unable to do so without that, most likely to prevent community spam)
